[language-server.rust-analyzer.config]
cargo.extraEnv.CARGO_TARGET_DIR = "/home/peach/cargo_target" 
checkOnSave.command = "clippy" 

[language-server.godot]
command = "nc"
args = ["127.0.0.1", "6005"]

[[language]]
name = "rust"

# [language.debugger]
# command = "codelldb"
# name = "codelldb"
# port-arg = "--port {}"
# transport = "tcp"

# [[language.debugger.templates]]
# name = "binary"
# request = "launch"

# [[language.debugger.templates.completion]]
# completion = "filename"
# name = "binary"

# [language.debugger.templates.args]
# program = "{0}"
# runInTerminal = true

[[language]]
name = "gdscript"
language-servers = ["godot"]
