#!/bin/bash
files_dir="$(dirname $(realpath "$0"))"

names=".bash_logout .bash_profile .bashrc .config/bash .config/git .config/helix .config/home-manager .config/sh .config/shell .config/tmux .config/zsh .profile .zshenv .zshrc"

if [ -z ${HOME+x} ]; then
  echo "HOME variable is unsetted"
  exit 1
fi

if [[ $1 == "-f" ]]; then
  force="true"
fi

unavailable_paths=""
if [[ $force != "true" ]]; then
  for name in $names; do
    path="$HOME/$name"

    if \
      [ ! -e "$path" ] \
      || { [ -L "$path" ] && [[ "$(readlink -f "$path")" =~ /nix/store* ]]; } \
      || { [ -L "$path" ] && [[ "$(readlink -f "$path")" == "$(readlink -f "$files_dir/$name")" ]]; } \
    then
      :
    else
      unavailable_paths="$path $unavailable_paths"
    fi
  done
fi

if [[ $unavailable_paths != "" ]]; then
  echo "These paths are not available for linking."
  echo "Please either remove, back them up, or use the -f flag to replace the files."
  echo "${unavailable_paths// /$'\n'}"
  exit 1
fi

linked="false"
for name in $names; do
  if [[ "$(readlink -f "$files_dir/$name")" != "$(readlink -f "$HOME/$name")" ]]; then
    if [ -e "$HOME/$name" ] || [ -L "$HOME/$name" ]; then
      rm "$HOME/$name"
      ln -s "$files_dir/$name" "$HOME/$name"
      echo "Replaced ~/$name"
    else
      ln -s "$files_dir/$name" "$HOME/$name"
      echo "Created ~/$name"
    fi
    linked="true"
  fi
done

if [[ $linked == "false" ]]; then
  echo "No new links were created"
fi


