#!/usr/bin/env zsh

. ~/.config/shell/interactive

eval "$(starship init zsh)"

# HYPHEN_INSENSITIVE="true"
# HIST_STAMPS="dd/mm/yyyy"

setopt AUTO_CD
setopt AUTO_PUSHD
setopt PUSHD_IGNORE_DUPS
setopt PUSHD_SILENT

source ~/.config/zsh/completion.zsh
source ~/.config/zsh/dirs.zsh
source ~/.config/zsh/helix.zsh
