#!/usr/bin/env zsh
. ~/.config/shell/login

[ -f "$XDG_STATE_HOME/zsh-history" ] || touch "$XDG_STATE_HOME/zsh-history"

export HISTFILE="$XDG_STATE_HOME/zsh-history"
export SAVEHIST="1000"
export HISTSIZE="1000"
