#!/usr/bin/env zsh

source ~/.config/shell/interactive

[ -d "$XDG_STATE_HOME/zsh" ] || mkdir -p "$XDG_STATE_HOME/zsh"
[ -f "$XDG_STATE_HOME/zsh/history" ] || touch "$XDG_STATE_HOME/zsh/history"

export HISTFILE="$XDG_STATE_HOME/zsh/history"
export SAVEHIST="2000"
export HISTSIZE="2000"

source ~/.config/zsh/completion.zsh

if has-command starship; then
  eval "$(starship init zsh)"

  PS2=$'%{\e[90m%}∙∙∙%{\e[0m%} '
fi

HYPHEN_INSENSITIVE="true"

source ~/.config/zsh/plugins.zsh

# For completions to work, this must be added after compinit is called.
if has-command zoxide; then
  eval "$(zoxide init zsh)"
fi

setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS

if has-command direnv; then
  eval "$(direnv hook zsh)"
fi
