#!/usr/bin/env zsh

. ~/.config/shell/interactive

[ -d "$XDG_STATE_HOME/zsh" ] || mkdir -p "$XDG_STATE_HOME/zsh"
[ -f "$XDG_STATE_HOME/zsh/history" ] || touch "$XDG_STATE_HOME/zsh/history"

export HISTFILE="$XDG_STATE_HOME/zsh/history"
export SAVEHIST="1000"
export HISTSIZE="1000"

if has_command starship; then
  eval "$(starship init zsh)"

  PS2=$'%{\e[90m%}∙∙∙%{\e[0m%} '
fi

# HYPHEN_INSENSITIVE="true"
# HIST_STAMPS="dd/mm/yyyy"

setopt AUTO_PUSHD
setopt PUSHD_IGNORE_DUPS
setopt PUSHD_SILENT

source ~/.config/zsh/completion.zsh
source ~/.config/zsh/dirs.zsh
source ~/.config/zsh/helix.zsh

# For completions to work, this must be added after compinit is called.
if has_command zoxide; then
  eval "$(zoxide init zsh)"
fi

setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS

if has_command direnv; then
  eval "$(direnv hook zsh)"
fi
