#!/usr/bin/env bash

. ~/.config/shell/interactive

[ -d "$XDG_STATE_HOME/bash" ] || mkdir -p "$XDG_STATE_HOME/bash"
[ -f "$XDG_STATE_HOME/bash/history" ] || touch "$XDG_STATE_HOME/bash/history"

export HISTFILE="$XDG_STATE_HOME/bash/history"
export HISTSIZE=1000
export HISTFILESIZE=1000

[ -f "$HOME/.bash_history" ] && rm "$HOME/.bash_history"

if has-command starship; then
  eval "$(starship init bash)"
fi

if has-command zoxide; then
  eval "$(zoxide init bash)"
fi
